INSERT INTO achievements (achievement, achievement_description) VALUES 
('Primer Animal Avistado', 'Has avistado tu primer animal.'),
('Primera Planta Avistada', 'Has avistado tu primera planta.'),
('Primer Parque Visitado', 'Has visitado tu primer parque nacional.'),
('3 Animales Avistados', 'Has avistado 3 animales endémicos.'),
('3 Plantas Avistadas', 'Has avistado 3 plantas endémicas.'),
('3 Parques Visitados', 'Has visitado 3 parques nacionales.'),
('5 Animales Avistados', 'Has avistado 5 animales endémicos.'),
('5 Plantas Avistadas', 'Has avistado 5 plantas endémicas.'),
('5 Parques Visitados', 'Has visitado 5 parques nacionales.'),
('10 Animales Avistados', 'Has avistado 10 animales endémicos.'),
('10 Plantas Avistadas', 'Has avistado 10 plantas endémicas.'),
('10 Parques Visitados', 'Has visitado 10 parques nacionales.'),
('15 Animales Avistados', 'Has avistado 15 animales endémicos.'),
('15 Plantas Avistadas', 'Has avistado 15 plantas endémicas.'),
('15 Parques Visitados', 'Has visitado 15 parques nacionales.'),
('20 Animales Avistados', 'Has avistado 20 animales endémicos.'),
('20 Plantas Avistadas', 'Has avistado 20 plantas endémicas.'),
('20 Parques Visitados', 'Has visitado 20 parques nacionales.'),
('25 Animales Avistados', 'Has avistado 25 animales endémicos.'),
('25 Plantas Avistadas', 'Has avistado 25 plantas endémicas.'),
('30 Animales Avistados', 'Has avistado 30 animales endémicos.'),
('35 Animales Avistados', 'Has avistado 35 animales endémicos.'),
('40 Animales Avistados', 'Has avistado 40 animales endémicos.'),
('Todos los Parques Visitados', 'Has visitado todos los parques nacionales.'),
('Todos los Animales Vistos', 'Has avistado todos los animales endémicos.'),
('Todas las Plantas Vistas', 'Has avistado todas las plantas endémicas.');
